package com.burning.springboot.entity;

import java.io.Serializable;
import java.util.Date;

public class Activity implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.activity_id
     *
     * @mbggenerated
     */
    private Long activityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.activity_name
     *
     * @mbggenerated
     */
    private String activityName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.activity_desc
     *
     * @mbggenerated
     */
    private String activityDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.begin_date_time
     *
     * @mbggenerated
     */
    private Date beginDateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.end_date_time
     *
     * @mbggenerated
     */
    private Date endDateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.stock_count
     *
     * @mbggenerated
     */
    private Integer stockCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.take_count
     *
     * @mbggenerated
     */
    private Integer takeCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.state
     *
     * @mbggenerated
     */
    private Byte state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.creator
     *
     * @mbggenerated
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.stock_surplus_count
     *
     * @mbggenerated
     */
    private Integer stockSurplusCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.strategy_id
     *
     * @mbggenerated
     */
    private Integer strategyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table activity
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.id
     *
     * @return the value of activity.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.id
     *
     * @param id the value for activity.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.activity_id
     *
     * @return the value of activity.activity_id
     *
     * @mbggenerated
     */
    public Long getActivityId() {
        return activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.activity_id
     *
     * @param activityId the value for activity.activity_id
     *
     * @mbggenerated
     */
    public void setActivityId(Long activityId) {
        this.activityId = activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.activity_name
     *
     * @return the value of activity.activity_name
     *
     * @mbggenerated
     */
    public String getActivityName() {
        return activityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.activity_name
     *
     * @param activityName the value for activity.activity_name
     *
     * @mbggenerated
     */
    public void setActivityName(String activityName) {
        this.activityName = activityName == null ? null : activityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.activity_desc
     *
     * @return the value of activity.activity_desc
     *
     * @mbggenerated
     */
    public String getActivityDesc() {
        return activityDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.activity_desc
     *
     * @param activityDesc the value for activity.activity_desc
     *
     * @mbggenerated
     */
    public void setActivityDesc(String activityDesc) {
        this.activityDesc = activityDesc == null ? null : activityDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.begin_date_time
     *
     * @return the value of activity.begin_date_time
     *
     * @mbggenerated
     */
    public Date getBeginDateTime() {
        return beginDateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.begin_date_time
     *
     * @param beginDateTime the value for activity.begin_date_time
     *
     * @mbggenerated
     */
    public void setBeginDateTime(Date beginDateTime) {
        this.beginDateTime = beginDateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.end_date_time
     *
     * @return the value of activity.end_date_time
     *
     * @mbggenerated
     */
    public Date getEndDateTime() {
        return endDateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.end_date_time
     *
     * @param endDateTime the value for activity.end_date_time
     *
     * @mbggenerated
     */
    public void setEndDateTime(Date endDateTime) {
        this.endDateTime = endDateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.stock_count
     *
     * @return the value of activity.stock_count
     *
     * @mbggenerated
     */
    public Integer getStockCount() {
        return stockCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.stock_count
     *
     * @param stockCount the value for activity.stock_count
     *
     * @mbggenerated
     */
    public void setStockCount(Integer stockCount) {
        this.stockCount = stockCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.take_count
     *
     * @return the value of activity.take_count
     *
     * @mbggenerated
     */
    public Integer getTakeCount() {
        return takeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.take_count
     *
     * @param takeCount the value for activity.take_count
     *
     * @mbggenerated
     */
    public void setTakeCount(Integer takeCount) {
        this.takeCount = takeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.state
     *
     * @return the value of activity.state
     *
     * @mbggenerated
     */
    public Byte getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.state
     *
     * @param state the value for activity.state
     *
     * @mbggenerated
     */
    public void setState(Byte state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.creator
     *
     * @return the value of activity.creator
     *
     * @mbggenerated
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.creator
     *
     * @param creator the value for activity.creator
     *
     * @mbggenerated
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.create_time
     *
     * @return the value of activity.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.create_time
     *
     * @param createTime the value for activity.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.update_time
     *
     * @return the value of activity.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.update_time
     *
     * @param updateTime the value for activity.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.stock_surplus_count
     *
     * @return the value of activity.stock_surplus_count
     *
     * @mbggenerated
     */
    public Integer getStockSurplusCount() {
        return stockSurplusCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.stock_surplus_count
     *
     * @param stockSurplusCount the value for activity.stock_surplus_count
     *
     * @mbggenerated
     */
    public void setStockSurplusCount(Integer stockSurplusCount) {
        this.stockSurplusCount = stockSurplusCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.strategy_id
     *
     * @return the value of activity.strategy_id
     *
     * @mbggenerated
     */
    public Integer getStrategyId() {
        return strategyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.strategy_id
     *
     * @param strategyId the value for activity.strategy_id
     *
     * @mbggenerated
     */
    public void setStrategyId(Integer strategyId) {
        this.strategyId = strategyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", activityId=").append(activityId);
        sb.append(", activityName=").append(activityName);
        sb.append(", activityDesc=").append(activityDesc);
        sb.append(", beginDateTime=").append(beginDateTime);
        sb.append(", endDateTime=").append(endDateTime);
        sb.append(", stockCount=").append(stockCount);
        sb.append(", takeCount=").append(takeCount);
        sb.append(", state=").append(state);
        sb.append(", creator=").append(creator);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", stockSurplusCount=").append(stockSurplusCount);
        sb.append(", strategyId=").append(strategyId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}